# Enable Powerlevel10k instant prompt. Should stay at the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh

# Set up the prompt

autoload -Uz promptinit
promptinit
prompt adam1

setopt histignorealldups sharehistory

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# Manual configuration

PATH=/root/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Plugins
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-sudo/sudo.plugin.zsh

# Functions

# Set 'man' colors
function man() {
    env \
    LESS_TERMCAP_mb=$'\e[01;31m' \
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[01;44;33m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    man "$@"
}

# fzf improvement
function fzf-lovely(){

	if [ "$1" = "h" ]; then
		fzf -m --reverse --preview-window down:20 --preview '[[ $(file --mime {}) =~ binary ]] &&
 	                echo {} is a binary file ||
	                 (bat --style=numbers --color=always {} ||
	                  highlight -O ansi -l {} ||
	                  coderay {} ||
	                  rougify {} ||
	                  cat {}) 2> /dev/null | head -500'

	else
	        fzf -m --preview '[[ $(file --mime {}) =~ binary ]] &&
	                         echo {} is a binary file ||
	                         (bat --style=numbers --color=always {} ||
	                          highlight -O ansi -l {} ||
	                          coderay {} ||
	                          rougify {} ||
	                          cat {}) 2> /dev/null | head -500'
	fi
}

#rm, pero borra true
function rmk(){
	scrub -p dod $1
	shred -zun 10 -v $1
}

#abrir cosas y desvincular de la terminal
function xopen() {
  for file in "$@"; do
    nohup xdg-open "$file" >/dev/null 2>&1 &
  done
}

#abrir cosas y cerrar terminal
function xopenk(){
  for file in "$@"; do
    nohup xdg-open "$file" >/dev/null 2>&1 &
  done
  sleep 1
  pkill -P $$ xdg-open
  exit
}

# Finalize Powerlevel10k instant prompt. Should stay at the bottom of ~/.zshrc.
(( ! ${+functions[p10k-instant-prompt-finalize]} )) || p10k-instant-prompt-finalize
source ~/powerlevel10k/powerlevel10k.zsh-theme

# Locale problemos
export LANGUAGE="en_US"
export LC_ALL="en_US.UTF-8"
export LC_MEASUREMENT="es_ES.UTF-8"
export LC_TIME="en_GB.UTF-8"
export LANG="en_US.UTF-8"

# Manual aliases
alias fzf='fzf-lovely'
alias ll='lsd -lh --group-dirs=first'
alias la='lsd -a --group-dirs=first'
alias l='lsd --group-dirs=first'
alias lla='lsd -lha --group-dirs=first'
alias ls='lsd --group-dirs=first'
alias cat='bat'
alias dc="cd .."

#abrir imagen en kitty
alias kittycat="kitty icat"

#calculadoras
alias matlab="matlab -nodesktop"
alias maxima="rlwrap maxima"

#qtile
alias qtile_conf="cp -f Documents/GitHUB/myArch/qtile/config.py .config/qtile && cp -f Documents/GitHUB/myArch/qtile/autostart.sh .config/qtile/"
alias qtile_reload="qtile cmd-obj -o cmd -f restart"
alias qtile_check="qtile check"
alias qtile_wall="feh --bg-fill "/home/BM4lex/.config/qtile/wallpaper.png""

#Ideapad power-porfiles:
alias power="cat /sys/firmware/acpi/platform_profile"
alias battery="echo 'low-power' > /sys/firmware/acpi/platform_profile"
alias perfomance="echo 'performance' > /sys/firmware/acpi/platform_profile"
alias balanced="echo 'balanced' > /sys/firmware/acpi/platform_profile"
alias battery_limit="cat /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode"
alias battery_limit_on="echo 1 > /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode"
alias battery_limit_off="echo 0 > /sys/bus/platform/drivers/ideapad_acpi/VPC2004:00/conservation_mode"
alias quick_charge_on="echo '\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x07' > /proc/acpi/call"
alias quick_charge_off="echo '\_SB.PCI0.LPC0.EC0.VPC0.SBMC 0x08' > /proc/acpi/call"

alias suspend="systemctl suspend"
alias shutdown="sudo shutdown now"

#add-on screen
alias hdmi-on="xrandr --output eDP --primary --mode 1920x1080 --pos 192x1080 --rotate normal --output HDMI-A-0 --mode 1920x1080 --pos 0x0 --rotate normal && feh --bg-scale .config/qtile/wallpaper.png DisplayPort-0"
alias hdmi-hub-on="xrandr --output eDP --primary --mode 1920x1080 --pos 192x1080 --rotate normal --output DisplayPort-0 --mode 1920x1080 --pos 0x0 --rotate normal && feh --bg-scale .config/qtile/wallpaper.png"
alias hdmi-on-right="xrandr --output eDP --primary --mode 1920x1080 --pos 0x81 --rotate normal --output HDMI-A-0 --mode 1920x1080 --pos 1632x0 --rotate normal && feh --bg-scale .config/qtile/wallpaper.png"
alias hdmi-hub-on-right="xrandr --output eDP --primary --mode 1920x1080 --pos 0x81 --rotate normal --output DisplayPort-0 --mode 1920x1080 --pos 1632x0 --rotate normal && feh --bg-scale .config/qtile/wallpaper.png"
alias hdmi-off="xrandr --output HDMI-A-0 --off && feh --bg-scale .config/qtile/wallpaper.png"
alias hdmi-hub-off="xrandr --output DisplayPort-0 --off && feh --bg-scale .config/qtile/wallpaper.png"
alias screenshot="maim -s | xclip -selection clipboard -t image/png"

#ssh error kitty
[ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"

#set up mouse and keyboard
alias set_mouse_keyboard="xinput set-prop \"MSFT0004:00 06CB:CD98 Touchpad\" \"libinput Natural Scrolling Enabled\" 1 & xinput set-prop \"MSFT0004:00 06CB:CD98 Touchpad\" \"libinput Tapping Enabled\" 1 & setxkbmap es"
